version: "3"
services:
  db:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: noredink
      POSTGRES_PASSWORD: noredink
  adminer:
    image: adminer
    ports:
      - 8080:8080
